name: "CI"

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.7"

      - run: "sudo apt update"

      - name: "Install Build Tools"
        run: "sudo apt install --yes build-essential gcc make clang-format"

      - name: "Install Documentation Tools"
        run: "sudo apt install --yes doxygen doxygen-gui doxygen-doc graphviz"

      - run: "gcc --version"

      - run: "make"
      - run: "make run"
      - run: "make test"
      - run: "make lint"
      - run: "make documentation"
      - run: "make set_version"
      - run: "make clean"

  lint-commit:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.7"
        with:
          fetch-depth: 0

      - uses: "wagoid/commitlint-github-action@v6.1.2"
